import {getFastDashboard} from '../lib/snapshot-service';
function money(n:number|null|undefined){return n==null?'—':'$'+n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function num(n:number|null){return n==null?'—':n.toFixed(2)+'×'}function chg(n:number|null){return n==null?'—':(n>=0?'+':'')+n.toFixed(2)+'%'}
function session(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const wd=p.find(x=>x.type==='weekday')?.value||'',t=Number(p.find(x=>x.type==='hour')?.value||0)*60+Number(p.find(x=>x.type==='minute')?.value||0);if(wd==='Sat'||wd==='Sun')return '已收盘';if(t>=240&&t<570)return '盘前';if(t>=570&&t<960)return '盘中';if(t>=960&&t<1200)return '盘后';return '已收盘'}
function valuation(ttm:number|null,fwd:number|null){if(ttm==null&&fwd==null)return '待更新';const p=fwd??ttm!;return p<20?'偏低':p>40?'偏高':'合理'}
export const dynamic='force-dynamic';
export default async function Home(){const d=await getFastDashboard(),s=session(),fear=d.fear;return <main>
<header><div><span className="eyebrow">US STOCK MONITOR · VALUATION & RISK</span><h1>美股估值与恐慌仪表盘</h1><p>最新可用行情 · TTM PE · Forward PE · VIX · 重大新闻</p></div><div className="pill"><i/>美东市场 <b>{s}</b></div></header>
<section className="marketGrid">{d.indices.map(x=><article className="marketCard" key={x.tracker}><div className="marketTop"><div><span className="kicker">{x.name}</span><h2>{x.tracker} <strong>{money(x.regularPrice??x.price)}</strong></h2></div><em className={(x.changePct??0)>=0?'up':'down'}>{chg(x.changePct)}</em></div><div className="quoteStrip"><div><small>收盘价</small><b>{money(x.regularPrice??x.price)}</b></div><div><small>盘后价</small><b>{money(x.postMarketPrice)}</b></div><div><small>数据时间</small><b>{x.quoteTime??x.asOf??'—'}</b></div></div><div className="metric4"><div><small>TTM PE</small><b>{num(x.ttmPe)}</b></div><div><small>Forward PE</small><b>{num(x.forwardPe)}</b></div><div><small>市场状态</small><b>{s}</b></div><div><small>行情日期</small><b>{x.asOf??'—'}</b></div></div><p className="cardNote">{x.note}</p></article>)}
<article className="marketCard fearCard"><div className="marketTop"><div><span className="kicker">CBOE VOLATILITY INDEX</span><h2>VIX <strong>{fear?.value?.toFixed(2)??'—'}</strong></h2></div><em>{fear?.change==null?'—':(fear.change>=0?'+':'')+fear.change.toFixed(2)}</em></div><div className="fearLevel"><b>{fear?.level??'数据等待'}</b><span>低波动 &lt;15 · 正常 15–20 · 紧张 20–30 · 恐慌 30–40 · 极端 ≥40</span></div><div className="fearScale"><i style={{left:Math.min(96,Math.max(4,((fear?.value??0)/50)*100))+'%'}}/></div><p className="cardNote">VIX · {fear?.asOf??'等待首次刷新'} · {fear?.source??'Yahoo/FRED'}</p></article></section>
<section className="summary"><div><small>观察股票</small><b>{d.stocks.length}</b></div><div><small>偏低</small><b>{d.stocks.filter(x=>valuation(x.ttmPe,x.forwardPe)==='偏低').length}</b></div><div><small>合理</small><b>{d.stocks.filter(x=>valuation(x.ttmPe,x.forwardPe)==='合理').length}</b></div><div><small>偏高</small><b>{d.stocks.filter(x=>valuation(x.ttmPe,x.forwardPe)==='偏高').length}</b></div><div><small>行情口径</small><b className="muted">收盘 / 盘后</b></div></section>
<div className="sectionTitle"><div><h2>七姐妹 · AI / 半导体</h2><p>Forward PE 优先；缺失时使用 TTM PE。</p></div><span>价格、盈利预期、新闻分层更新</span></div>
<div className="table"><div className="thead"><span>公司</span><span>最新价</span><span>涨跌</span><span>TTM PE</span><span>Forward PE</span><span>EPS预期30D</span><span>数据日期</span><span>估值</span></div>{d.stocks.map(x=>{const v=valuation(x.ttmPe,x.forwardPe);return <div className="stock" key={x.symbol}><div className="identity"><b>{x.symbol}</b><small>{x.name} · {x.group}</small></div><strong>{money(x.price)}</strong><span className={(x.changePct??0)>=0?'up':'down'}>{chg(x.changePct)}</span><span>{num(x.ttmPe)}</span><span>{num(x.forwardPe)}</span><span>{x.epsRevision30d==null?'—':chg(x.epsRevision30d)}</span><span>{x.tradeDate??'待更新'}</span><em className={'tag '+(v==='偏低'?'low':v==='偏高'?'high':'')}>{v}</em></div>})}</div>
<div className="columns"><section className="panel"><h2>重大新闻 / 事件</h2>{d.events.length?d.events.map((e,i)=><article className="event" key={e.title+i}><span>{e.symbol}</span><div><b>{e.title}</b><p>{e.note}</p><small>{e.source} · {e.time}</small></div></article>):<p>等待新闻刷新。</p>}</section><section className="panel methodology"><h2>数据口径</h2><p><b>涨跌幅：</b>（当日最终 regular-session close ÷ 上一交易日最终 regular-session close − 1）×100%。</p><p><b>盘后价：</b>Yahoo Chart 扩展时段最后一个有效价格，与收盘价分开显示。</p><p><b>TTM PE：</b>最新价格 ÷ 最近12个月 EPS。</p><p><b>Forward PE：</b>最新价格 ÷ Forward EPS。</p><p><b>VIX：</b>Yahoo ^VIX，失败时回退 FRED/CBOE。</p></section></div>
<section className="source"><b>数据管线</b><span className="ok">● Neon Snapshot</span><span>行情：Yahoo Chart / Alpha Vantage fallback</span><span>基本面：Yahoo quoteSummary</span><span>VIX：Yahoo/FRED</span></section>
<footer><b>最近行情日：</b>{d.tradeDate??'—'} · <b>快照生成：</b>{d.updatedAt?new Date(d.updatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—'}（北京时间）。本站为个人信息与估值观察工具，不构成投资建议。</footer>
</main>}
