import {getDashboardData} from '../lib/enriched-data';
function money(n:number|null){return n==null?'—':'$'+n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}
function num(n:number|null,s='×'){return n==null?'—':n.toFixed(2)+s}
function pct(n:number|null){return n==null?'—':n.toFixed(0)+'%'}
function temp(p:number|null){const pos=p==null?50:Math.max(3,Math.min(97,p));const label=p==null?'等待历史数据':p<30?'偏低':p>70?'偏高':'中性';return <><div className={'thermo '+(p==null?'disabled':'')}><span className="dot" style={{left:`${pos}%`}}/><small>低估</small><small>中性</small><small>高估</small></div><div className="tempCaption">估值温度（5Y PE 分位） · <b>{label}</b></div></>}
export const dynamic='force-dynamic';
export default async function Home(){const d=await getDashboardData();return <main>
<header><div><span className="eyebrow">US VALUATION · EOD · V2.3</span><h1>美股科技估值仪表盘</h1><p>市场整体 → 主题股票 → 当天事件 · 估值与情绪分开 · 数据不足不猜测</p></div><div className="pill"><i/>最近交易日 <b>{d.tradeDate??'等待数据'}</b></div></header>
<section className="marketGrid">{d.indices.map(x=><article className="marketCard" key={x.tracker}><div className="marketTop"><div><span className="kicker">{x.name}</span><h2>{x.tracker} <strong>{money(x.price)}</strong></h2></div><em className={(x.changePct??0)>=0?'up':'down'}>{x.changePct==null?'—':`${x.changePct>=0?'+':''}${x.changePct.toFixed(2)}%`}</em></div><div className="metric4"><div><small>TTM PE</small><b>{num(x.ttmPe)}</b></div><div><small>Forward PE</small><b>{num(x.forwardPe)}</b></div><div><small>5Y 分位</small><b>{pct(x.percentile5y)}</b></div><div><small>10Y 分位</small><b>{pct(x.percentile10y)}</b></div></div>{temp(x.percentile5y)}<p className="cardNote"><b>估值数据截至 {x.asOf??'—'}</b> · {x.note}</p></article>)}</section>
<section className="summary"><div><small>观察股票</small><b>{d.stocks.length}</b></div><div><small>估值偏低</small><b>{d.stocks.filter(x=>x.label==='估值偏低').length}</b></div><div><small>中性</small><b>{d.stocks.filter(x=>x.label==='中性').length}</b></div><div><small>估值偏高</small><b>{d.stocks.filter(x=>x.label==='估值偏高').length}</b></div><div><small>市场情绪</small><b className="muted">{d.sentiment.label}</b></div></section>
<div className="sectionTitle"><div><h2>七姐妹 · AI / 半导体</h2><p>正式口径：TTM PE = EOD 收盘价 ÷ 最近12个月 Diluted EPS；5Y 分位基于自身过去5年月度 TTM PE 序列。</p></div><span>P30 偏低 · P30–70 中性 · P70 偏高</span></div>
<div className="table"><div className="thead"><span>公司</span><span>收盘价</span><span>当日</span><span>TTM PE</span><span>Forward PE</span><span>5Y分位</span><span>估值观察</span></div>{d.stocks.map(x=><div className="stock" key={x.symbol}><div className="identity"><b>{x.symbol}</b><small>{x.name} · {x.group}</small></div><strong>{money(x.price)}</strong><span className={(x.changePct??0)>=0?'up':'down'}>{x.changePct==null?'—':`${x.changePct>=0?'+':''}${x.changePct.toFixed(2)}%`}</span><span>{num(x.ttmPe)}</span><span>{num(x.forwardPe)}</span><span>{pct(x.percentile5y)}</span><em className={'tag '+(x.label==='估值偏低'?'low':x.label==='估值偏高'?'high':'')}>{x.label}</em></div>)}</div>
<div className="columns"><section className="panel"><div className="sectionTitle compact"><div><h2>当天重点事件</h2><p>事件与价格因果分开表述。</p></div></div>{d.events.map(e=><article className="event" key={e.title}><span>{e.symbol}</span><div><b>{e.title}</b><p>{e.note}</p><small>{e.source} · {e.time}</small></div></article>)}</section><section className="panel methodology"><h2>V2 数据口径</h2><p><b>价格：</b>EOD Provider → 正常交易时段收盘价。</p><p><b>TTM EPS：</b>SEC EDGAR XBRL → 最近四个季度 Diluted EPS / 可核验的 TTM 口径。</p><p><b>TTM PE：</b>本站计算；TTM EPS ≤ 0 时显示“不适用”。</p><p><b>历史分位：</b>当前 PE 在过去5年自身月度有效 PE 序列中的百分位，至少36个月有效观察值才启用。</p><p><b>指数：</b>QQQ 与 S&P 500 使用指数/基金级可靠口径，绝不把成分股 PE 简单平均。</p></section></div>
<section className="source"><b>自动更新</b><span className="ok">● Vercel Cron 已配置</span><span>计划：每日 22:00 UTC</span><span>Hobby 实际可能在该小时内触发</span><span>行情 Provider 未授权前自动拒绝写入</span></section>
<footer><b>当前状态：</b>V2.3 已加入免费历史估值重建：配置 Alpha Vantage 免费 API Key 后，使用月度复权价格 + 历史季度 EPS 自动计算个股 TTM PE、5Y 分位和估值观察。当前收盘价仍为展示快照；Forward PE 不伪造。本站仅用于信息与估值观察，不构成投资建议。</footer>
</main>}
