import type {GlobalIndex} from './types';
const ITEMS=[['上证指数','000001.SS','中国','Asia/Shanghai','约30分钟'],['日经225','^N225','日本','Asia/Tokyo','延迟行情'],['韩国KOSPI','^KS11','韩国','Asia/Seoul','延迟行情'],['越南VN-Index','^VNINDEX.VN','越南','Asia/Ho_Chi_Minh','约15分钟']] as const;
function parts(epoch:number,tz:string){const p=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(epoch*1000)),g=(k:string)=>p.find(x=>x.type===k)?.value||'';return {date:g('year')+'-'+g('month')+'-'+g('day'),mins:Number(g('hour'))*60+Number(g('minute'))}}
function state(tz:string){const p=new Intl.DateTimeFormat('en-US',{timeZone:tz,weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()),g=(k:string)=>p.find(x=>x.type===k)?.value||'',wd=g('weekday'),m=Number(g('hour'))*60+Number(g('minute'));if(wd==='Sat'||wd==='Sun')return '休市' as const;const open=tz==='Asia/Shanghai'?(m>=570&&m<690)||(m>=780&&m<900):tz==='Asia/Tokyo'?(m>=540&&m<690)||(m>=750&&m<930):tz==='Asia/Seoul'?(m>=540&&m<930):(m>=540&&m<690)||(m>=780&&m<900);return open?'盘中' as const:'已收盘' as const}
async function scrapeShanghai():Promise<GlobalIndex>{const headers={'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15','Accept':'text/html,application/xhtml+xml','Accept-Language':'zh-CN,zh;q=0.9'};const sources=[['https://stocks.sina.cn/sh/?big=2&code=sh000001&timer=5&vt=1','新浪财经网页'],['https://www.eastmoney.com/','东方财富网页']] as const;for(const [url,source] of sources){try{const r=await fetch(url,{cache:'no-store',headers});if(!r.ok)continue;const h=(await r.text()).replace(/<script[\\s\\S]*?<\\/script>/gi,' ').replace(/<style[\\s\\S]*?<\\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/\\s+/g,' ');let price:number|null=null,pct:number|null=null,asOf:string|null=null;if(source==='新浪财经网页'){const pm=h.match(/最新[:：]\\s*([0-9,.]+)/),cm=h.match(/涨跌[:：]\\s*([+-]?[0-9,.]+)\\s*\\(\\s*([+-]?[0-9.]+)%\\s*\\)/),tm=h.match(/更新时间[:：]\\s*([0-9-]+\\s+[0-9:]+)/);price=pm?Number(pm[1].replace(/,/g,'')):null;pct=cm?Number(cm[2]):null;asOf=tm?tm[1]:null}else{const m=h.match(/上证指数\\s*([0-9,.]+)\\s*([+-]?[0-9,.]+)\\s*([+-]?[0-9.]+)%/);price=m?Number(m[1].replace(/,/g,'')):null;pct=m?Number(m[3]):null;asOf=null}if(price!=null&&price>0&&pct!=null&&Number.isFinite(pct))return {name:'上证指数',symbol:'000001.SH',market:'中国',timeZone:'Asia/Shanghai',price,changePct:pct,asOf,status:state('Asia/Shanghai'),source:source+'抓取 · 同页快照',delay:'网页行情'}}catch(e){console.error('Shanghai scrape failed',source,e)}}return {name:'上证指数',symbol:'000001.SH',market:'中国',timeZone:'Asia/Shanghai',price:null,changePct:null,asOf:null,status:'数据等待',source:'新浪/东方财富网页抓取',delay:'等待网页行情'}}

async function one(x:typeof ITEMS[number]):Promise<GlobalIndex>{const [name,symbol,market,timeZone,delay]=x;try{const u='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?range=5d&interval=5m';const r=await fetch(u,{cache:'no-store',headers:{'User-Agent':'Mozilla/5.0 (compatible; PersonalStockDashboard/1.0)','Accept':'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);const z=(await r.json())?.chart?.result?.[0],ts:number[]=z?.timestamp||[],cl:(number|null)[]=z?.indicators?.quote?.[0]?.close||[];
const points:{epoch:number;date:string;price:number}[]=[];for(let i=0;i<ts.length;i++){const price=Number(cl[i]);if(Number.isFinite(price)&&price>0){const p=parts(ts[i],timeZone);points.push({epoch:ts[i],date:p.date,price})}}if(!points.length)throw new Error('no valid intraday points');
const latest=points[points.length-1],dates=[...new Set(points.map(p=>p.date))].sort(),prevDate=[...dates].reverse().find(d=>d<latest.date);if(!prevDate)throw new Error('previous trading day missing');const prevPoints=points.filter(p=>p.date===prevDate),prev=prevPoints[prevPoints.length-1];const changePct=(latest.price/prev.price-1)*100,asOf=new Intl.DateTimeFormat('zh-CN',{timeZone,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(latest.epoch*1000));return {name,symbol,market,timeZone,price:latest.price,changePct,asOf,status:state(timeZone),source:'Yahoo Finance 5m · same-series calculation',delay}}catch(e){console.error('global index failed',symbol,e);return {name,symbol,market,timeZone,price:null,changePct:null,asOf:null,status:'数据等待',source:'Yahoo Finance 5m',delay}}}
export async function fetchGlobalIndices(){const shanghai=scrapeShanghai();const rest=ITEMS.slice(1).map(one);return Promise.all([shanghai,...rest])}
