import {alphaVantage,finite} from './alpha-vantage';
import type {StockSnapshot,MarketIndex} from './types';
type Q={price:number;changePct:number|null;date:string;quoteTime:string|null;source:string;mode:'live'|'delayed'|'eod';regularPrice:number;preMarketPrice:number|null;postMarketPrice:number|null};
function etSession(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const wd=p.find(x=>x.type==='weekday')?.value||'',t=Number(p.find(x=>x.type==='hour')?.value||0)*60+Number(p.find(x=>x.type==='minute')?.value||0);if(wd==='Sat'||wd==='Sun')return '已收盘' as const;if(t>=240&&t<570)return '盘前' as const;if(t>=570&&t<960)return '盘中' as const;if(t>=960&&t<1200)return '盘后' as const;return '已收盘' as const}
function et(epoch:number){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(epoch*1000)),g=(k:string)=>p.find(x=>x.type===k)?.value||'';return {date:g('year')+'-'+g('month')+'-'+g('day'),mins:Number(g('hour'))*60+Number(g('minute'))}}
async function yjson(symbol:string){const u='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?range=2d&interval=5m&includePrePost=true';const r=await fetch(u,{cache:'no-store',headers:{'User-Agent':'Mozilla/5.0 (compatible; PersonalStockDashboard/1.0)','Accept':'application/json'}});if(!r.ok)throw new Error('Yahoo HTTP '+r.status);const z=(await r.json())?.chart?.result?.[0];if(!z)throw new Error('Yahoo empty');return z}
async function nasdaq(symbol:string):Promise<Q>{const to=new Date(),from=new Date(Date.now()-12*86400000);const fmt=(d:Date)=>(d.getMonth()+1)+'/'+d.getDate()+'/'+d.getFullYear();const u='https://api.nasdaq.com/api/quote/'+encodeURIComponent(symbol)+'/historical?assetclass='+(symbol==='QQQ'||symbol==='SPY'?'etf':'stocks')+'&fromdate='+encodeURIComponent(fmt(from))+'&todate='+encodeURIComponent(fmt(to))+'&limit=10';const r=await fetch(u,{cache:'no-store',headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36','Accept':'application/json, text/plain, */*','Referer':'https://www.nasdaq.com/','Accept-Language':'en-US,en;q=0.9'}});if(!r.ok)throw new Error('Nasdaq HTTP '+r.status);const j=await r.json(),rows:any[]=j?.data?.tradesTable?.rows||[];const parsed=rows.map(x=>({date:String(x.date||''),close:Number(String(x.close||'').replace(/[$,]/g,''))})).filter(x=>x.date&&Number.isFinite(x.close)&&x.close>0);if(parsed.length<2)throw new Error('Nasdaq historical unavailable '+symbol);const cur=parsed[0],prev=parsed[1],pct=(cur.close/prev.close-1)*100;return {price:cur.close,changePct:pct,date:new Date(cur.date+' 12:00:00').toISOString().slice(0,10),quoteTime:cur.date+' close',source:'Nasdaq Historical Quotes',mode:'eod',regularPrice:cur.close,preMarketPrice:null,postMarketPrice:null}}
async function yahoo(symbol:string):Promise<Q>{const z=await yjson(symbol),m=z.meta||{},price=Number(m.regularMarketPrice),prev=Number(m.previousClose);if(!Number.isFinite(price)||price<=0||!Number.isFinite(prev)||prev<=0)throw new Error('invalid Yahoo regular/previous close '+symbol);const epoch=Number(m.regularMarketTime)||0,date=epoch?et(epoch).date:'';const pct=(price/prev-1)*100;const ts:Array<number>=z.timestamp||[],cl:Array<number|null>=z.indicators?.quote?.[0]?.close||[];let pre:number|null=null,post:number|null=null;for(let i=ts.length-1;i>=0;i--){if(cl[i]==null)continue;const c=Number(cl[i]),p=et(ts[i]);if(!Number.isFinite(c)||c<=0||p.date!==date)continue;if(post==null&&p.mins>960&&p.mins<1200)post=c;if(pre==null&&p.mins>=240&&p.mins<570)pre=c}return {price,changePct:pct,date,quoteTime:date?date+' 16:00 ET':null,source:'Yahoo Finance Chart · regularMarketPrice/previousClose',mode:'delayed',regularPrice:price,preMarketPrice:pre,postMarketPrice:post}}
async function av(symbol:string):Promise<Q>{const j=await alphaVantage('GLOBAL_QUOTE',symbol),x=j['Global Quote']||{},price=finite(x['05. price']);if(price==null||price<=0)throw new Error('Quote unavailable '+symbol);return {price,changePct:finite(String(x['10. change percent']||'').replace('%','')),date:String(x['07. latest trading day']||''),quoteTime:null,source:'Alpha Vantage fallback',mode:'eod',regularPrice:price,preMarketPrice:null,postMarketPrice:null}}
async function quote(symbol:string){try{return await nasdaq(symbol)}catch(e){console.error('Nasdaq quote failed',symbol,e);try{return await yahoo(symbol)}catch(y){console.error('Yahoo quote failed',symbol,y);return av(symbol)}}}
export async function refreshQuote(stock:StockSnapshot):Promise<StockSnapshot>{const q=await quote(stock.symbol),s=etSession(),display=s==='盘前'&&q.preMarketPrice!=null?q.preMarketPrice:s==='盘后'&&q.postMarketPrice!=null?q.postMarketPrice:q.regularPrice;return {...stock,price:display,regularPrice:q.regularPrice,preMarketPrice:q.preMarketPrice,postMarketPrice:q.postMarketPrice,changePct:q.changePct,tradeDate:q.date||stock.tradeDate,ttmPe:stock.ttmEps!=null&&stock.ttmEps>0?display/stock.ttmEps:stock.ttmPe,forwardPe:stock.forwardEps!=null&&stock.forwardEps>0?display/stock.forwardEps:stock.forwardPe,session:s,priceMode:q.mode,source:q.source}}
export async function refreshIndexQuote(index:MarketIndex):Promise<MarketIndex>{try{const q=await quote(index.tracker);return {...index,price:q.regularPrice,regularPrice:q.regularPrice,postMarketPrice:q.postMarketPrice,quoteTime:q.quoteTime,changePct:q.changePct,asOf:q.date||index.asOf,status:'ok',note:'收盘价与前收优先取 Nasdaq Historical Quotes 两个交易日 Close 并自行计算涨跌幅；失败时回退 Yahoo / Alpha Vantage。'}}catch(e){console.error('index quote failed',index.tracker,e);return index}}
