import {alphaVantage,finite} from './alpha-vantage';
import type {StockSnapshot,MarketIndex} from './types';
type Q={price:number;changePct:number|null;date:string;quoteTime:string|null;source:string;mode:'live'|'delayed'|'eod';regularPrice:number;preMarketPrice:number|null;postMarketPrice:number|null};
function etSession(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const wd=p.find(x=>x.type==='weekday')?.value||'',t=Number(p.find(x=>x.type==='hour')?.value||0)*60+Number(p.find(x=>x.type==='minute')?.value||0);if(wd==='Sat'||wd==='Sun')return '已收盘' as const;if(t>=240&&t<570)return '盘前' as const;if(t>=570&&t<960)return '盘中' as const;if(t>=960&&t<1200)return '盘后' as const;return '已收盘' as const}
function et(epoch:number){const p=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(epoch*1000)),g=(k:string)=>p.find(x=>x.type===k)?.value||'';return {date:g('year')+'-'+g('month')+'-'+g('day'),mins:Number(g('hour'))*60+Number(g('minute'))}}
async function yjson(symbol:string,interval:string,range:string,pre=false){const u='https://query1.finance.yahoo.com/v8/finance/chart/'+encodeURIComponent(symbol)+'?range='+range+'&interval='+interval+(pre?'&includePrePost=true':'');const r=await fetch(u,{cache:'no-store',headers:{'User-Agent':'Mozilla/5.0 (compatible; PersonalStockDashboard/1.0)','Accept':'application/json'}});if(!r.ok)throw new Error('Yahoo HTTP '+r.status);const z=(await r.json())?.chart?.result?.[0];if(!z)throw new Error('Yahoo empty');return z}
async function yahoo(symbol:string):Promise<Q>{const d=await yjson(symbol,'1d','10d');const dts:Array<number>=d.timestamp||[],dc:Array<number|null>=d.indicators?.quote?.[0]?.close||[];const bars=dts.map((t,i)=>({t,price:Number(dc[i])})).filter(x=>Number.isFinite(x.price));if(bars.length<2)throw new Error('Yahoo daily bars unavailable');const cur=bars.at(-1)!,prev=bars.at(-2)!,date=et(cur.t).date;const pct=(cur.price/prev.price-1)*100;let pre:number|null=null,post:number|null=null;try{const i=await yjson(symbol,'5m','2d',true),ts:Array<number>=i.timestamp||[],cl:Array<number|null>=i.indicators?.quote?.[0]?.close||[];for(let n=ts.length-1;n>=0;n--){const c=Number(cl[n]);if(!Number.isFinite(c))continue;const p=et(ts[n]);if(p.date!==date)continue;if(post==null&&p.mins>960&&p.mins<1200)post=c;if(pre==null&&p.mins>=240&&p.mins<570)pre=c}}catch{}return {price:cur.price,changePct:pct,date,quoteTime:date+' 16:00 ET',source:'Yahoo Finance · daily close + extended chart',mode:'delayed',regularPrice:cur.price,preMarketPrice:pre,postMarketPrice:post}}
async function av(symbol:string):Promise<Q>{const j=await alphaVantage('GLOBAL_QUOTE',symbol),x=j['Global Quote']||{},price=finite(x['05. price']);if(price==null)throw new Error('Quote unavailable '+symbol);return {price,changePct:finite(String(x['10. change percent']||'').replace('%','')),date:String(x['07. latest trading day']||''),quoteTime:null,source:'Alpha Vantage fallback',mode:'eod',regularPrice:price,preMarketPrice:null,postMarketPrice:null}}
async function quote(symbol:string){try{return await yahoo(symbol)}catch(e){console.error('Yahoo quote failed',symbol,e);return av(symbol)}}
export async function refreshQuote(stock:StockSnapshot):Promise<StockSnapshot>{const q=await quote(stock.symbol),s=etSession(),display=s==='盘前'&&q.preMarketPrice!=null?q.preMarketPrice:s==='盘后'&&q.postMarketPrice!=null?q.postMarketPrice:q.price;return {...stock,price:display,regularPrice:q.regularPrice,preMarketPrice:q.preMarketPrice,postMarketPrice:q.postMarketPrice,changePct:q.changePct,tradeDate:q.date||stock.tradeDate,ttmPe:stock.ttmEps!=null&&stock.ttmEps>0?display/stock.ttmEps:stock.ttmPe,forwardPe:stock.forwardEps!=null&&stock.forwardEps>0?display/stock.forwardEps:stock.forwardPe,session:s,priceMode:q.mode,source:q.source}}
export async function refreshIndexQuote(index:MarketIndex):Promise<MarketIndex>{const q=await quote(index.tracker);return {...index,price:q.regularPrice,regularPrice:q.regularPrice,postMarketPrice:q.postMarketPrice,quoteTime:q.quoteTime,changePct:q.changePct,asOf:q.date||index.asOf,status:'ok',note:'收盘价与涨跌幅取 Yahoo 日线相邻两个交易日 Close；盘后价单独取 5 分钟扩展时段。'}}
